/**
 * WMS Tasks - 200 mandays over 40 working days
 * Team: Diana Prince (SA), Clark Kent (SA), Barry Allen (PG), Hal Jordan (PG), Oliver Queen (PG)
 */

import type { MockTask } from './mock-data'

export const wmsTasks: MockTask[] = [
  // Week 1-2: Foundation & Setup (40 mandays)
  {
    id: 'wms-1',
    projectId: '2',
    title: 'Database Schema Design',
    description: 'Design comprehensive database schema for WMS including all entities',
    status: 'done',
    priority: 'critical',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['database', 'architecture'],
    milestone: 'Phase 1',
    dueDate: '2024-01-15',
    startDate: '2024-01-10',
    timeEstimate: 16,
    timeSpent: 15,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-1'
  },
  {
    id: 'wms-2',
    projectId: '2',
    title: 'Setup Development Environment',
    description: 'Configure dev environment, CI/CD pipeline, and code repository',
    status: 'done',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['devops', 'setup'],
    milestone: 'Phase 1',
    dueDate: '2024-01-12',
    startDate: '2024-01-10',
    timeEstimate: 8,
    timeSpent: 8,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-1'
  },
  {
    id: 'wms-3',
    projectId: '2',
    title: 'API Framework Setup',
    description: 'Setup REST API framework with authentication and base structure',
    status: 'done',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'api'],
    milestone: 'Phase 1',
    dueDate: '2024-01-17',
    startDate: '2024-01-13',
    timeEstimate: 12,
    timeSpent: 12,
    epicId: 'wms-epic-5'
  },
  {
    id: 'wms-4',
    projectId: '2',
    title: 'Frontend Framework Setup',
    description: 'Setup React/Next.js with UI component library',
    status: 'done',
    priority: 'high',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['frontend', 'setup'],
    milestone: 'Phase 1',
    dueDate: '2024-01-16',
    startDate: '2024-01-12',
    timeEstimate: 8,
    timeSpent: 8,
    epicId: 'wms-epic-4'
  },
  {
    id: 'wms-5',
    projectId: '2',
    title: 'User Authentication Module',
    description: 'Implement JWT-based authentication with role management',
    status: 'done',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'security'],
    milestone: 'Phase 1',
    dueDate: '2024-01-20',
    startDate: '2024-01-17',
    timeEstimate: 12,
    timeSpent: 11,
    epicId: 'wms-epic-1'
  },

  // Week 3-4: Inbound Operations (50 mandays)
  {
    id: 'wms-6',
    projectId: '2',
    title: 'Goods Receipt API',
    description: 'Create API endpoints for receiving goods with barcode validation',
    status: 'in_progress',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'inbound'],
    milestone: 'Phase 2',
    dueDate: '2024-01-27',
    startDate: '2024-01-22',
    timeEstimate: 16,
    timeSpent: 10,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-1'
  },
  {
    id: 'wms-7',
    projectId: '2',
    title: 'Goods Receipt UI',
    description: 'Build receiving screen with barcode scanner integration',
    status: 'in_progress',
    priority: 'high',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['frontend', 'inbound'],
    milestone: 'Phase 2',
    dueDate: '2024-01-29',
    startDate: '2024-01-24',
    timeEstimate: 12,
    timeSpent: 6,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-1'
  },
  {
    id: 'wms-8',
    projectId: '2',
    title: 'Location Assignment Logic',
    description: 'Implement auto-assignment algorithm based on product characteristics',
    status: 'in_progress',
    priority: 'critical',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['backend', 'algorithm'],
    milestone: 'Phase 2',
    dueDate: '2024-02-02',
    startDate: '2024-01-28',
    timeEstimate: 16,
    timeSpent: 8,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-2'
  },
  {
    id: 'wms-9',
    projectId: '2',
    title: 'Put-away Process',
    description: 'Implement put-away workflow with mobile guidance',
    status: 'todo',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['backend', 'inbound'],
    milestone: 'Phase 2',
    dueDate: '2024-02-05',
    startDate: '2024-02-01',
    timeEstimate: 14,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-2'
  },
  {
    id: 'wms-10',
    projectId: '2',
    title: 'Quality Inspection Module',
    description: 'QC workflow with photo capture and approval process',
    status: 'todo',
    priority: 'medium',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['frontend', 'quality'],
    milestone: 'Phase 2',
    dueDate: '2024-02-07',
    startDate: '2024-02-03',
    timeEstimate: 12,
    epicId: 'wms-epic-1',
    requirementId: 'wms-req-1'
  },

  // Week 5-6: Inventory Management (45 mandays)
  {
    id: 'wms-11',
    projectId: '2',
    title: 'Inventory Tracking System',
    description: 'Real-time inventory tracking with lot/serial number support',
    status: 'todo',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'inventory'],
    milestone: 'Phase 3',
    dueDate: '2024-02-14',
    startDate: '2024-02-08',
    timeEstimate: 18,
    epicId: 'wms-epic-2',
    requirementId: 'wms-req-3'
  },
  {
    id: 'wms-12',
    projectId: '2',
    title: 'Inventory Dashboard',
    description: 'Real-time inventory levels with drill-down capability',
    status: 'todo',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['frontend', 'inventory'],
    milestone: 'Phase 3',
    dueDate: '2024-02-16',
    startDate: '2024-02-10',
    timeEstimate: 14,
    epicId: 'wms-epic-2',
    requirementId: 'wms-req-3'
  },
  {
    id: 'wms-13',
    projectId: '2',
    title: 'Cycle Counting Module',
    description: 'Automated cycle count scheduling and variance reporting',
    status: 'todo',
    priority: 'high',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['backend', 'inventory'],
    milestone: 'Phase 3',
    dueDate: '2024-02-20',
    startDate: '2024-02-15',
    timeEstimate: 16,
    epicId: 'wms-epic-2',
    requirementId: 'wms-req-4'
  },
  {
    id: 'wms-14',
    projectId: '2',
    title: 'Expiry Date Management',
    description: 'Track expiry dates with FEFO logic and alerts',
    status: 'todo',
    priority: 'medium',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['backend', 'inventory'],
    milestone: 'Phase 3',
    dueDate: '2024-02-22',
    startDate: '2024-02-18',
    timeEstimate: 12,
    epicId: 'wms-epic-2',
    requirementId: 'wms-req-3'
  },

  // Week 7-8: Outbound Operations (55 mandays)
  {
    id: 'wms-15',
    projectId: '2',
    title: 'Order Management System',
    description: 'Order import, validation, and allocation logic',
    status: 'todo',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'outbound'],
    milestone: 'Phase 4',
    dueDate: '2024-02-28',
    startDate: '2024-02-23',
    timeEstimate: 16,
    epicId: 'wms-epic-3',
    requirementId: 'wms-req-5'
  },
  {
    id: 'wms-16',
    projectId: '2',
    title: 'Wave Planning',
    description: 'Wave creation with order grouping and optimization',
    status: 'todo',
    priority: 'high',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['backend', 'outbound'],
    milestone: 'Phase 4',
    dueDate: '2024-03-02',
    startDate: '2024-02-26',
    timeEstimate: 14,
    epicId: 'wms-epic-3',
    requirementId: 'wms-req-5'
  },
  {
    id: 'wms-17',
    projectId: '2',
    title: 'Pick Path Optimization',
    description: 'Algorithm to minimize travel distance for pickers',
    status: 'todo',
    priority: 'high',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['backend', 'algorithm'],
    milestone: 'Phase 4',
    dueDate: '2024-03-06',
    startDate: '2024-03-02',
    timeEstimate: 16,
    epicId: 'wms-epic-3',
    requirementId: 'wms-req-5'
  },
  {
    id: 'wms-18',
    projectId: '2',
    title: 'Picking Mobile UI',
    description: 'Mobile interface for pick list execution',
    status: 'todo',
    priority: 'critical',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['mobile', 'outbound'],
    milestone: 'Phase 4',
    dueDate: '2024-03-08',
    startDate: '2024-03-04',
    timeEstimate: 14,
    epicId: 'wms-epic-4',
    requirementId: 'wms-req-5'
  },
  {
    id: 'wms-19',
    projectId: '2',
    title: 'Packing Station Module',
    description: 'Packing verification and label printing',
    status: 'todo',
    priority: 'high',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['frontend', 'outbound'],
    milestone: 'Phase 4',
    dueDate: '2024-03-12',
    startDate: '2024-03-08',
    timeEstimate: 12,
    epicId: 'wms-epic-3',
    requirementId: 'wms-req-6'
  },
  {
    id: 'wms-20',
    projectId: '2',
    title: 'Shipping Integration',
    description: 'Integrate with carrier APIs (FedEx, UPS, DHL)',
    status: 'todo',
    priority: 'high',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'integration'],
    milestone: 'Phase 4',
    dueDate: '2024-03-15',
    startDate: '2024-03-11',
    timeEstimate: 14,
    epicId: 'wms-epic-5',
    requirementId: 'wms-req-7'
  },

  // Week 9-10: Mobile App & Advanced Features (50 mandays)
  {
    id: 'wms-21',
    projectId: '2',
    title: 'Mobile App Framework',
    description: 'Setup React Native with offline-first architecture',
    status: 'todo',
    priority: 'critical',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['mobile', 'setup'],
    milestone: 'Phase 5',
    dueDate: '2024-03-20',
    startDate: '2024-03-16',
    timeEstimate: 16,
    epicId: 'wms-epic-4',
    requirementId: 'wms-req-11'
  },
  {
    id: 'wms-22',
    projectId: '2',
    title: 'Barcode Scanner Integration',
    description: 'Integrate camera-based and hardware barcode scanners',
    status: 'todo',
    priority: 'critical',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['mobile', 'hardware'],
    milestone: 'Phase 5',
    dueDate: '2024-03-22',
    startDate: '2024-03-18',
    timeEstimate: 12,
    epicId: 'wms-epic-4',
    requirementId: 'wms-req-10'
  },
  {
    id: 'wms-23',
    projectId: '2',
    title: 'RFID Reader Integration',
    description: 'Support RFID tag reading for bulk scanning',
    status: 'todo',
    priority: 'medium',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['mobile', 'hardware'],
    milestone: 'Phase 5',
    dueDate: '2024-03-26',
    startDate: '2024-03-22',
    timeEstimate: 14,
    epicId: 'wms-epic-4',
    requirementId: 'wms-req-10'
  },
  {
    id: 'wms-24',
    projectId: '2',
    title: 'Offline Sync Mechanism',
    description: 'Implement offline data storage and sync when online',
    status: 'todo',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['mobile', 'sync'],
    milestone: 'Phase 5',
    dueDate: '2024-03-28',
    startDate: '2024-03-24',
    timeEstimate: 16,
    epicId: 'wms-epic-4',
    requirementId: 'wms-req-11'
  },

  // Week 11-12: Integration & Reporting (40 mandays)
  {
    id: 'wms-25',
    projectId: '2',
    title: 'ERP Integration Framework',
    description: 'Build integration layer for SAP/Oracle ERP systems',
    status: 'todo',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['backend', 'integration'],
    milestone: 'Phase 6',
    dueDate: '2024-04-03',
    startDate: '2024-03-29',
    timeEstimate: 18,
    epicId: 'wms-epic-5',
    requirementId: 'wms-req-15'
  },
  {
    id: 'wms-26',
    projectId: '2',
    title: 'E-commerce Integration',
    description: 'Connect with Shopify, WooCommerce, Magento',
    status: 'todo',
    priority: 'high',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['backend', 'integration'],
    milestone: 'Phase 6',
    dueDate: '2024-04-06',
    startDate: '2024-04-01',
    timeEstimate: 16,
    epicId: 'wms-epic-5',
    requirementId: 'wms-req-16'
  },
  {
    id: 'wms-27',
    projectId: '2',
    title: 'Dashboard & KPI Module',
    description: 'Real-time dashboard with warehouse performance metrics',
    status: 'todo',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['frontend', 'reporting'],
    milestone: 'Phase 6',
    dueDate: '2024-04-10',
    startDate: '2024-04-05',
    timeEstimate: 14,
    epicId: 'wms-epic-6',
    requirementId: 'wms-req-12'
  },
  {
    id: 'wms-28',
    projectId: '2',
    title: 'Inventory Reports',
    description: 'Stock level, aging, movement, and valuation reports',
    status: 'todo',
    priority: 'medium',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['frontend', 'reporting'],
    milestone: 'Phase 6',
    dueDate: '2024-04-12',
    startDate: '2024-04-08',
    timeEstimate: 12,
    epicId: 'wms-epic-6',
    requirementId: 'wms-req-13'
  },

  // Week 13-14: Testing & Optimization (20 mandays)
  {
    id: 'wms-29',
    projectId: '2',
    title: 'Unit Testing',
    description: 'Write comprehensive unit tests for all modules',
    status: 'todo',
    priority: 'high',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['testing', 'quality'],
    milestone: 'Phase 7',
    dueDate: '2024-04-18',
    startDate: '2024-04-13',
    timeEstimate: 16,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-30',
    projectId: '2',
    title: 'Integration Testing',
    description: 'End-to-end testing of complete workflows',
    status: 'todo',
    priority: 'high',
    assignee: '5',
    assigneeName: 'Hal Jordan',
    labels: ['testing', 'quality'],
    milestone: 'Phase 7',
    dueDate: '2024-04-20',
    startDate: '2024-04-15',
    timeEstimate: 14,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-31',
    projectId: '2',
    title: 'Performance Optimization',
    description: 'Optimize database queries and API response times',
    status: 'todo',
    priority: 'medium',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['performance', 'optimization'],
    milestone: 'Phase 7',
    dueDate: '2024-04-24',
    startDate: '2024-04-20',
    timeEstimate: 12,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-32',
    projectId: '2',
    title: 'Security Audit',
    description: 'Security review and penetration testing',
    status: 'todo',
    priority: 'critical',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['security', 'testing'],
    milestone: 'Phase 7',
    dueDate: '2024-04-26',
    startDate: '2024-04-22',
    timeEstimate: 14,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-33',
    projectId: '2',
    title: 'User Acceptance Testing',
    description: 'UAT with warehouse staff and stakeholders',
    status: 'todo',
    priority: 'high',
    assignee: '2',
    assigneeName: 'Diana Prince',
    labels: ['testing', 'uat'],
    milestone: 'Phase 7',
    dueDate: '2024-04-30',
    startDate: '2024-04-26',
    timeEstimate: 16,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-34',
    projectId: '2',
    title: 'Documentation',
    description: 'User manual, API docs, and deployment guide',
    status: 'todo',
    priority: 'medium',
    assignee: '4',
    assigneeName: 'Barry Allen',
    labels: ['documentation'],
    milestone: 'Phase 7',
    dueDate: '2024-05-03',
    startDate: '2024-04-29',
    timeEstimate: 12,
    epicId: 'wms-epic-1'
  },
  {
    id: 'wms-35',
    projectId: '2',
    title: 'Production Deployment',
    description: 'Deploy to production environment with monitoring',
    status: 'todo',
    priority: 'critical',
    assignee: '3',
    assigneeName: 'Clark Kent',
    labels: ['deployment', 'production'],
    milestone: 'Phase 7',
    dueDate: '2024-05-06',
    startDate: '2024-05-04',
    timeEstimate: 8,
    epicId: 'wms-epic-1'
  }
]
